# Generated by Django 6.0 on 2025-12-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_employment_means_alter_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interviewer',
            new_name='interviewer_name',
        ),
    ]
