# Generated by Django 6.0 on 2025-12-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.application'),
        ),
    ]
