# Generated by Django 6.0 on 2025-12-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_date']},
        ),
    ]
