# Generated by Django 6.0 on 2025-12-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobposting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover-letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for the employer', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='JobAppQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_prompt', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('Short Answer', 'Short Answer'), ('Long Answer', 'Long Answer'), ('Number', 'Number'), ('Date', 'Date'), ('Yes/No', 'Yes/No'), ('Choices', 'Choices')], default='Long Answer', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='JobAppAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobappquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'question'), name='unique_answer_per_question')],
            },
        ),
    ]
