# Generated by Django 6.0 on 2026-01-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_application_cover_letter_application_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('SM', 'Small Business (1-50)'), ('MD', 'Medium Company (51-500)'), ('LG', 'Large Enterprise (501+)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
