# Generated by Django 6.0 on 2026-01-04 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_company_company_size_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_invalid_after',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
