# Generated by Django 6.0 on 2026-01-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_profile_token_invalid_after'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token_invalid_after',
            new_name='token_invalid_before',
        ),
    ]
