# Generated by Django 6.0.1 on 2026-01-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_token_invalid_after_profile_token_invalid_before'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobappanswer',
            name='unique_answer_per_question',
        ),
        migrations.RemoveField(
            model_name='jobappquestion',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.DeleteModel(
            name='JobAppAnswer',
        ),
        migrations.DeleteModel(
            name='JobAppQuestion',
        ),
    ]
