# Generated by Django 6.0.1 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_jobappanswer_unique_answer_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('MXN', 'Mexican Peso')], default='USD', max_length=3),
        ),
    ]
